---
chdir: /home/deploy/apps/rolling_stock/current
environment: production
address: localhost
port: 3002
timeout: 30
wait: 10
log: /home/deploy/apps/rolling_stock/shared/log/thin.log
pid: /home/deploy/apps/rolling_stock/shared/pids/thin.pid
socket: /tmp/rolling_stock-thin.sock
max_conns: 1024
max_persistent_conns: 200
require: []
servers: 1
daemonize: true
